theme: jekyll-theme-slate
title: Setsunablog
baseurl: ""
url: "http://blog.family-402.top"

twitter_username: Setsuna51183
github_username:  Setsuna-Kitahara
email: Setsuna_Kitahara@outlook.com

SEOTitle: Setsunablog
header-img: images/bg.jpg
description: "Code by Setsuna Kitahara"

sidebar: true
sidebar-about-description: "一个漏网的白学家"
sidebar-avatar: images/avatar.png

featured-tags: true
featured-condition-size: 0

chrome-tab-theme-color: "#000000"
service-worker: true

permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true

gems: [jekyll-paginate]

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM 


