theme: jekyll-theme-slate
title: Setsunablog
brief-intro: Blogging as I like
baseurl: ""
url: http://blog.family-402.top

twitter_username: #Setsuna51183
github_username:  Setsuna-Kitahara
email: Setsuna_Kitahara@outlook.com

SEOTitle: Setsunablog
header-img: images/bg.jpg
description: "Code by Setsuna Kitahara"

sidebar: true
sidebar-about-description: "一个漏网的白学家"
sidebar-avatar: images/avatar.png